server:
  port: 8083

spring:
  application:
    name: taskflow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distribution?serverTimezone=GMT%2b8
    username: root
    password: 3271149877mm
  jackson:
    default-property-inclusion: non_null # JSON?????????

mybatis-plus:
  type-aliases-package: com.taskflow.entity # ?????
  mapper-locations: classpath:mapper/*.xml

logging:
  level:

    org.springframework.jdbc.core: WARN  # ?? JDBC ????? WARN
    org.springframework.scheduling: INFO  # ?????????????? INFO



